language: node_js
node_js:
- '8'

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Caching-with-npm
cache:
  directories:
  - node_modules

# generated via "travis setup heroku" | after "travis login --github-token TOKEN" and "heroku login" @ https://github.com/acdcjunior/docker-heroku-travis
#
# PS> docker run --rm -it -v ${PWD}:/c3pr -w /c3pr acdcjunior/heroku-travis bash
# root@a2717d1d78da:/c3pr# heroku login
# ------------------ enter email and password
# root@a2717d1d78da:/c3pr# travis login --github-token TOKEN
# root@a2717d1d78da:/c3pr# travis setup heroku --force
#
deploy:
  provider: heroku
  api_key:
    secure: aMwlspjxF3y9aUZqgRqktlwvmMY/pFrfywFiZOsb+y/6OQHgALdsWPwwqOi/ETOyqvmM2lZHXFQu9dnL6t3c1Nozo+MD6T+bbmqR5blPuTvxRmILzmSsKc51mlZwSnilP/s325oQ6ZQ/t49FSaTFbrPe1E33vp4mrOveiQhktilVwPsNosQyWnq3gtJGudPdqTGZ89LoMt3w2Mo0Fcv3zTvM6RSw63ymb9NNcl3n4ObL9w5+ad6vNnRIsFz9Gd1Vjq7WgImLotNAmmOdiI9Zr0xJp6eu3+8NlERIVFToVsrlibk3ms8vUDAdBqX7JaWgZKEoW7Y6hVnA+3Z2bAjMV+zT5GKde143aNnjRCwqsc7LK6IqQ74txsnAVoH6BlRr0IquTUUyTLmGhUn5CwxjXp1RlvcXBJkgh4AnBjCKk5lmqlFEBWOGwuC12cyD07PCu3DUltLv7+/I4ExFdYts1YV7i8Jw2EoZpSyVy7ZTribITVE8FmAFR5HFG5OqpdLkUS28cBgnvw/GJW1xmw7PkMzz1BfLny7SftcPFIA0eBtwBBPK3Dtyl19J1l1M7hyEnA25qN1/y4C3dC6l0QlFXWClBLXWUpgvoIkK95pPpp9d3H5cbvWNgL2LKif2gLqO1yh06MtJlmdxuL88eHRnIh5fyexLIqH417AzhmkuRIw=
  app: c3pr-brain
  on:
    repo: c3pr/c3pr-brain
