language: node_js
node_js:
- '8'

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Caching-with-npm
cache:
  directories:
  - node_modules

# generated via "travis setup heroku" | after "travis login --github-token TOKEN" and "heroku login" @ https://github.com/acdcjunior/docker-heroku-travis
deploy:
  provider: heroku
  api_key:
    secure: WnTkMlY9hgTjlfmu4gXbBrTB9uvBxrAV3Aymirz0EmIE7zcJPFDgtLKJrmNJxu+JnTxYMxwBZ7GM9rBTliL2CniFpG67K5z1kiNkiagC4kRly6du2qLRQK4WJsde0rLNmLruo0kQjRatLIfsQzEixre16Mls/xl48gJyaHfCpoozmhedBBia6W/a+C9HiBwzA9DO4xSQAYufPhcn3ggtWlscaNpMpKWRq1BIqUkb/h0yIWm5pGAdUDz8lpW7y5C718hAyYrfMCEFGND2IOJulVSWkEyQ5/9FGOv5Bys5Ze/P/G6CGSZFC2YKoWwI0wtcsiMBNfiNONgRh55lx3/Ub6xRXha3dKBEu3ZGGF/bkFWFlmg9RYp2T09LIAG7BtBDXFY0r8rn+8zHcSerZjmn6I7BUf47nqE/L6Mntv+RTlVEMT4ucswCQc20IYPIFid3Le6in9z9FGEz4nRCLQ9JvKJR6wITHbTGXgWCBQu40HehhwtEYqQ2vYBKUlSxtyEXXd+02xjYyZBZDqbg0xFP12ojOlvLGoBC1+Iz/dy4/Qmm0wRR10DOb3LAK4Pf3U6WtG4fk13Y/aN94RiyXtzZi3eSgyKAMTA26yAw273AameqQtuPuH3eROe5F+wceZshd8JPzXSJbJvI0FClqRjoSZK2dij4dp7CIxB6n4Tnoto=
  app: c3pr-adapter-github
  on:
    repo: c3pr/c3pr-adapter-github
