language: node_js
node_js:
- '8'

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Caching-with-npm
cache:
  directories:
  - node_modules

# generated via "travis setup heroku" | after "travis login --github-token TOKEN" and "heroku login" @ https://github.com/acdcjunior/docker-heroku-travis
deploy:
  provider: heroku
  api_key:
    secure: hbDhuyk3K4cjHlqw0pT3hbZqPic8wpVCfkue+KaFF9PLhI3wiYjzKml1ACuYsGn9V5RHqSKljQYvURJAH50JeCHQA13b2W1H1eXZEeEJkDieAl7RJVpWCFFITLH/F38cjghtuFQmd9kRSYtJfTxxoK2HEdffD1NKBYLz5HnVuMmxOlHdZIKR95gefrBdFvX5rF3N+7E4aUG2O3Ue57oeJbDbgnTIHO3ITd83IjCubfrr+yyx8I0E7d/vzuPU81w942wKEixCRAwmTQD6wg1X7ecDMN3J2JEzMbgaxv8Dxh5TQCHIesllMhKguN76OipzsBAbrv9yO+Rg1LnoTatyuljqnc1CmFdG3kmRkEayCAEMGTTpVVIy7i0TAuG9UzrGLuLFz0Y6WleUTT+UedgJlawZZoAC8Z9JTItTwQHNHl9yc9cPn7ByAKWMVqfcLpPLgyjihJMAyJWI5PdPzoQwxjzTjxB7dHlfa/TeapqRCyxTheaxNHhBdNLlA6k1Gi41UofLM2j3z763/Q6vnRaJP+xbpxhfdILzQcVhaaAmlK2oQq6W7qwoZ/J/y+fU+L7y0LBcSXgjpCGYshsSp0KuJJgLRE/kYOxP4nwVNUhlobZvT+uTqVg2tPnb7r3atE1Wb+qwFlOey726x1kjAuNoTkRLcPKTOyjZeaQ7W57a+Fs=
  app: c3pr
  on:
    repo: c3pr/c3pr
