language: node_js
node_js:
  - "9"

services:
  - docker

script:
  - npm ci
  - npm run build
  - docker build -t c3pr/c3pr-dashboard-ui .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push c3pr/c3pr-dashboard-ui
