### Authorization by token, part 1. Retrieve and save token.
POST http://127.0.0.1:7300/api/v1/login
Content-Type: application/json

{"username": "http-client", "password": "pass"}

> {% client.global.set("auth_token", response.body); %}

###
GET http://127.0.0.1:7300/api/v1/events/ChangesCommitted?payload.project_uuid=6068bb20-6145-4e3c-a9d3-2096fd2db24b
Authorization: Bearer {{auth_token}}

###
GET http://127.0.0.1:7300/api/v1/logs/euuid/9312e1aa-418a-4424-8dc7-6d3ecbe45cc9
Authorization: Bearer {{auth_token}}

###
GET http://127.0.0.1:7300/api/v1/logs/sha/37359043bb3a17114b6c3652bed25e1fed639dc7
Authorization: Bearer {{auth_token}}
###

PATCH http://localhost:7300/api/v1/projects/5b36aa1e6e3cbc0006213b97
Authorization: Bearer {{auth_token}}

###
GET http://localhost:7300/api/v1/projects
Authorization: Bearer {{auth_token}}
###

GET http://localhost:7300/api/v1/projects?uuid=6068bb20-6145-4e3c-a9d3-2096fd2db24b
Authorization: Bearer {{auth_token}}
###

PATCH http://localhost:7305/api/hub/api/v1/projects/5b36aa1e6e3cbc0006213b97
Authorization: Bearer {{auth_token}}

###
POST http://localhost:7300/api/v1/events/ToolInvocationFailed/reprocess-parents
Authorization: Bearer {{auth_token}}

###
GET http://localhost:7300/api/v1/events/ChangesCommitted/d1fd8808-9496-44b0-a259-20e6a7115e3d
Authorization: Bearer {{auth_token}}

###
GET http://localhost:7300/api/v1/events/?uuid=4c3d2741-dd7d-45da-a9b0-25818d7c193e
Authorization: Bearer {{auth_token}}

###
GET http://localhost:7300/api/v1/events/?payload.project_uuid=1eb106d7-188d-499b-8acc-ffd630c5688a
Authorization: Bearer {{auth_token}}

###
############################# project_files
GET http://localhost:7300/api/v1/projects/6068bb20-6145-4e3c-a9d3-2096fd2db24b/files
Authorization: Bearer {{auth_token}}
###
GET http://localhost:7300/api/v1/projects/6068bb20-6145-4e3c-a9d3-2096fd2db24b/files/
Authorization: Bearer {{auth_token}}
###
GET http://localhost:7300/api/v1/projects/6068bb20-6145-4e3c-a9d3-2096fd2db24b/files/files/src/main/java/com/stuff/HelloApplication.java
Authorization: Bearer {{auth_token}}
###
PATCH http://localhost:7300/api/v1/projects/6068bb20-6145-4e3c-a9d3-2096fd2db24b/files/src/main/java/com/stuff/HelloApplication.java
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
    "project_uuid": "6068bb20-6145-4e3c-a9d3-2096fd2db24b",
    "file_path": "src/main/java/com/stuff/HelloApplication.java",
    "analyses": [],
    "excluded_for_tools": [{
      "all_tools": true,
      "all_lines": true,
      "reason": "App file should never be touched!!!"
    }]
}
###
PUT http://localhost:7300/api/v1/projects/6068bb20-6145-4e3c-a9d3-2096fd2db24b/files/src/main/java/com/stuff/HelloApplication3.java
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
    "project_uuid": "6068bb20-6145-4e3c-a9d3-2096fd2db24b",
    "file_path": "src/main/java/com/stuff/HelloApplication3.java",
    "analyses": [],
    "excluded_for_tools": [{
      "all_tools": true,
      "all_lines": true,
      "reason": "App2 file should never be touched!x2"
    }]
}
###