# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://127.0.0.1:5000/api/v1/login
Content-Type: application/json

{}

###

GET http://127.0.0.1:5000/api/v1/projects/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWVlMWU3NC1hZTdlLTQzMTItYmM5Yy0xNGViMjZmYWJlMTAiLCJpc3MiOiJjM3ByLWh1YiIsInBlcm1pc3Npb25zIjoicmVnaXN0ZXItZXZlbnRzIn0.B5ARdhOcV-b0qKxb6kX9Yr4Vr1SWvxm2sNYDfbYard4

###

GET http://127.0.0.1:5000/api/v1/projects/7ac33816-c794-4cf3-a5b4-5f7e2ff06543/prs
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWVlMWU3NC1hZTdlLTQzMTItYmM5Yy0xNGViMjZmYWJlMTAiLCJpc3MiOiJjM3ByLWh1YiIsInBlcm1pc3Npb25zIjoicmVnaXN0ZXItZXZlbnRzIn0.B5ARdhOcV-b0qKxb6kX9Yr4Vr1SWvxm2sNYDfbYard4

###

GET http://127.0.0.1:5000/api/v1/projects/7ac33816-c794-4cf3-a5b4-5f7e2ff06543/prs/open/changed_files
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWVlMWU3NC1hZTdlLTQzMTItYmM5Yy0xNGViMjZmYWJlMTAiLCJpc3MiOiJjM3ByLWh1YiIsInBlcm1pc3Npb25zIjoicmVnaXN0ZXItZXZlbnRzIn0.B5ARdhOcV-b0qKxb6kX9Yr4Vr1SWvxm2sNYDfbYard4

###

