### Authorization by token, part 1. Retrieve and save token.
POST http://127.0.0.1:7300/api/v1/login
Content-Type: application/json

{"username": "http-client", "password": "pass"}

> {% client.global.set("auth_token", response.body); %}

###
GET http://127.0.0.1:7300/api/v1/events/ChangesCommitted?payload.project_uuid=6068bb20-6145-4e3c-a9d3-2096fd2db24b
Authorization: Bearer {{auth_token}}

###

GET http://127.0.0.1:7300/api/v1/logs/id/f10c022e8f4e722aabfe6653cedbbabcdbfb820a
Authorization: Bearer {{auth_token}}

###

PATCH http://localhost:7300/api/v1/projects/5b36aa1e6e3cbc0006213b97
Authorization: Bearer {{auth_token}}

###

PATCH http://localhost:7305/api/hub/api/v1/projects/5b36aa1e6e3cbc0006213b97
Authorization: Bearer {{auth_token}}

###
POST http://localhost:7300/api/v1/events/ToolInvocationFailed/reprocess-parents
Authorization: Bearer {{auth_token}}

###
GET http://localhost:7300/api/v1/events/ChangesCommitted/d1fd8808-9496-44b0-a259-20e6a7115e3d
Authorization: Bearer {{auth_token}}

###
