### Authorization by token, part 1. Retrieve and save token.
POST http://127.0.0.1:7300/api/v1/login
Content-Type: application/json

{"username": "http-client", "password": "pass"}

> {% client.global.set("auth_token", response.body); %}

###
GET http://127.0.0.1:7300/api/v1/events/ChangesCommitted?payload.project_uuid=6068bb20-6145-4e3c-a9d3-2096fd2db24b
Authorization: Bearer {{auth_token}}

###
